a = int(input("Your FirstNum : "))
b = int(input("Your SecondNum : "))
c1 = a + b
c2 = a - b
c3 = a * b
c4 = a / b
print(a ,"+" , b , "=" , c1)
print(a ,"-" , b , "=" , c2)
print(a ,"*" , b , "=" , c3)
print(a ,"/" , b , "=" , c4)
